### ISSUE TITLE
require('iotivity-node') hangs in non-REPL mode

### ISSUE THREAD

**Issue by qiuzhong** [otcshare/iotivity-node#113]
# Steps:
1. In node REPL mode, require('iotivity-node') works well:
	```
	# node
	> require('iotivity-node');
	{ platform: [Getter/Setter],
	  device: [Getter/Setter],
	  client: 
	   Client {
		 getDeviceInfo: [Function],
		 getPlatformInfo: [Function],
		 create: [Function],
		 retrieve: [Function],
		 update: [Function],
		 delete: [Function],
		 findDevices: [Function],
		 findPlatforms: [Function],
		 findResources: [Function],
		 _events: { newListener: [Function], removeListener: [Function] },
		 _eventsCount: 2 },
	  server: Server {} }
	```

2. Run this require statement in node with <strong>-e</strong> options, it will hang
	```
	# node -e "require('iotivity-node');"

	```
	It doesn't return. 
	
# Test environments
* [IoT-ref-kit image #101](http://iot-ref-kit.ostc.intel.com/download/builds/intel-iot-refkit_master/2017-02-06_04-34-54-build-101/images/intel-corei7-64/refkit-image-gateway-intel-corei7-64.wic.xz)
* iotivity-node 1.2.0-1 in this image.

**Comment by gabrielschulhof** [comment]
That's because `setInterval()` is called on startup. There is, however, no requirement that iotivity-node work with `node -e`.

**Comment by qiuzhong** [comment]
Running test.js with one require statement still hangs.

**Comment by gabrielschulhof** [comment]
Yes, I know. There is no way of exiting, because we have no specification for shutting down the stack. Thus, your only way out is `process.exit(0)`.

**Comment by qiuzhong** [comment]
Thanks. With <code>process.exit(0)</code> it can exit. I am curious why in iotivity-node-1.1.1-3 on Ostro image, <code>node test.js</code> can return in several seconds.

**Comment by qiuzhong** [comment]
@gabrielschulhof 

For the same require statement:
```
$ cat test.js
require('iotivity-node');
```

For iotivity-node 1.1.1-3, <code>node test.js</code> can return.
```
# node test.js
# echo $?
0
```

For iotivity-node 1.2.0-1, <code>node test.js</code> will hang.
```
# node test.js

```

So is this the spec change and acceptable? Could you give us an explanation for this?

**Comment by gabrielschulhof** [comment]
IIRC 1.1.1 was structured such that you had to
```JS
var ocf = require( "iotivity-node" );
var client = ocf( "client" );
```
Thus, `require( "iotivity-node" )` merely loaded the module, but it did not start the `setInterval()` until you called `ocf( "client" )`.

In contrast, 1.2.0 is structured such that `setInterval()` is started as part of the iotivity-node loading process. That is, `setInterval()` is started by calling `require( "iotivity-node" )`. This is in accordance with the latest spec, whereby no extra function call beyond the `require( "iotivity-node" )` is necessary in order to initialize iotivity-node for use either as a client or as a server.

AFAIK there is no requirement that I defer initialization until the library is actually used.
