### ISSUE TITLE
Sensor server implementation should know the size of observers list

### ISSUE THREAD

**Issue by nagineni** [otcshare/iotivity-node#24]
server.notify call is there to notify observers with data and state changes, but there is no way to check 
whether the observers list is empty or not. 

Provide an event to check the size of observers list, so that we can make sure that 'server.notify' is called only when the observers list is not empty.

**Comment by zolkis** [comment]
I assumed this check could be hidden by the JS shim, so that developers only provide when they want to notify.

However, it may have other use cases to expose the list of observers to a resource. I need to check on this.

Theoretically the 'server.notify' call is not needed to be exposed in the high level API, if the implementation can detect writes to read-write properties: it could fire itself the notifications if there are any observers. Then the code using the server API needs only to update the resource representation of the sensor by writing to its properties, without caring to manually notify. 

But since notify is a side effect, we may want a separate API call for it. And once we have that method, we indeed also need to tell if there are observers.
