### ISSUE TITLE
force push to master

### ISSUE THREAD

**Issue by pohly** [otcshare/iotivity-node#48]
@gabrielschulhof apparently you just did a force push to master, wiping out all references to the previous released versions.

Was that intentional?

Which revision of iotivity-node should meta-iot-web use now?

**Comment by gabrielschulhof** [comment]
@pohly I did that when I created a repo on iotivity.org. Since iotivty uses gerrit, you can't just transfer existing commits. So, I had no choice but to break the chain on master. Still, there are [tags](https://github.com/otcshare/iotivity-node/releases) pointing at the old tree. I have since made a release from the new tree (1.1.0-1).
