### ISSUE TITLE
CLIENT vs CLIENT_SERVER discovery

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#77]
OCInit - OCMode.OC_CLIENT vs  OCMode.OC_CLIENT_SERVER mode

Discovery of devices lists all OCF resources in OC_CLIENT case
Discovery of devices lists only resources starting with URL /oic  in CLIENT_SERVER case

**Comment by gabrielschulhof** [comment]
Actually, my experience has been that in OC_CLIENT mode it lists all resources, whereas in OC_CLIENT_SERVER mode it also lists all resources, but there is another server: the client, since it has resources in the same process, because the client is also the server.

Branch secure-1.2.0 runs both the client and the server in OC_CLIENT_SERVER mode and I have been able to make the tests pass that way.

**Comment by iamsanjeev** [comment]
So recommend switch to secure-1.2.0 ?

**Comment by gabrielschulhof** [comment]
Not necessarily. I created secure-1.2.0 in anticipation of iotivity's eventual move away from supporting ```SECURED=0```. The branch is significantly different in that it requires that you ```OCRegisterPersistentStorageHandler()``` and that you provide ACLs for all the resources on your server. If you just want OC_CLIENT_SERVER, branch 1.2.0 should work. Lemme throw a quick branch up on travis to see if I can reproduce your issue.

**Comment by iamsanjeev** [comment]
That will help. Make sure you have a set of non /oic resource uri like /a/example/iotivity-node etc.

**Comment by gabrielschulhof** [comment]
Oh, of course! In the tests, a UUID is generated for each test and given to both the client(s) and the server(s) participating in the test. The client then does a discovery until it finds a resource by the name ```/a/<uuid-given>``` and that's when it knows that it found the corresponding test server. It then proceeds to test all kinds of requests.

Let's see how https://travis-ci.org/otcshare/iotivity-node/builds/165159094, which tests ebd74b849a93e64a83313e318ca31e79da8ff665, turns out.

**Comment by gabrielschulhof** [comment]
From the build it looks like OC_CLIENT_SERVER works. Can you confirm? Also, please ignore the last job (OSX). I'll remove it from the buildbot, because we're not really supporting OSX.

**Comment by iamsanjeev** [comment]
Checking again. It works. I wonder...hmmm.
Very likely mistake in my script.
